
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rentoffice
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - "3001:3000"
  #   env_file: .env
  #   command: >
  #     sh -c "
  #     npx prisma migrate deploy &&
  #     npm run start:prod
  #     "
  #   volumes:
  #     - .:/app

volumes:
  postgres_data:
